// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCMYGU3IIRh66jSfaw-usqkgIlfYNGdHk',
    appId: '1:99513276497:web:a44f72b7c7ec536ddac070',
    messagingSenderId: '99513276497',
    projectId: 'realestate-47011',
    authDomain: 'realestate-47011.firebaseapp.com',
    storageBucket: 'realestate-47011.firebasestorage.app',
    measurementId: 'G-KVJ2CWGHS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnTcjexzMGKcMIGvm-jGim-vJo0ZV7XME',
    appId: '1:99513276497:android:51ed2443e48f7ef9dac070',
    messagingSenderId: '99513276497',
    projectId: 'realestate-47011',
    storageBucket: 'realestate-47011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmRzNMdlTxQ7-_yawoygwFlUJH3g4f2VY',
    appId: '1:99513276497:ios:ebbcf1a5594965a2dac070',
    messagingSenderId: '99513276497',
    projectId: 'realestate-47011',
    storageBucket: 'realestate-47011.firebasestorage.app',
    iosBundleId: 'com.orre.mmc.orreMmcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmRzNMdlTxQ7-_yawoygwFlUJH3g4f2VY',
    appId: '1:99513276497:ios:ebbcf1a5594965a2dac070',
    messagingSenderId: '99513276497',
    projectId: 'realestate-47011',
    storageBucket: 'realestate-47011.firebasestorage.app',
    iosBundleId: 'com.orre.mmc.orreMmcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCMYGU3IIRh66jSfaw-usqkgIlfYNGdHk',
    appId: '1:99513276497:web:d3977dd0ccd24ae6dac070',
    messagingSenderId: '99513276497',
    projectId: 'realestate-47011',
    authDomain: 'realestate-47011.firebaseapp.com',
    storageBucket: 'realestate-47011.firebasestorage.app',
    measurementId: 'G-7T9E5LJP5Q',
  );
}
